#!/usr/bin/env bash

red="\e[31m"
green="\e[32m"
blue="\e[34m"
reset="\e[39m"

errors=0

deps=(
	bluez-utils # bluetoothctl
	brightnessctl
	fzf
	networkmanager # nmcli
	otf-commit-mono-nerd
)

printf() {
	command printf "$@" >&2
}

install_deps() {
	printf "%bInstalling deps...%b\n" "$blue" "$reset"

	local dep
	for dep in "${deps[@]}"; do
		if pacman -Qi "$dep" &> /dev/null; then
			printf "[=] %s\n" "$dep"
		else
			printf "[ ] %s...\n" "$dep"

			if sudo pacman -S --noconfirm "$dep"; then
				printf "[%b+%b] %s\n" "$green" "$reset" "$dep"
			else
				printf "[%bx%b] %s\n" "$red" "$reset" "$dep"
				((errors += 1))
			fi
		fi
	done
}

restart_waybar() {
	printf "\n%bRestarting Waybar...%b\n" "$blue" "$reset"

	pkill waybar
	~/.config/waybar/scripts/run &> /dev/null &
	disown
}

main() {
	install_deps
	restart_waybar

	if ((errors > 0)); then
		printf "\nFinished with %b%d error(s)%b\n" \
			"$red" "$errors" "$reset"
	else
		printf "\n%bDone%b\n" "$green" "$reset"
	fi
}

main
