#!/usr/bin/env bash
#
# Scan, select, pair, and connect to Bluetooth devices
# Passing "off" powers off Bluetooth
#
# Requires bluez-utils (bluetoothctl) and fzf
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 19, 2025
# License: MIT

TIMEOUT=20
LOG_FILE="/tmp/yudots-bluetooth.log"

printf() {
	command printf "$@" >&2
}

fzf_ghostty() {
	env -u FZF_DEFAULT_OPTS -u FZF_DEFAULT_OPTS_FILE \
		fzf \
			--color='fg:-1,bg:-1,list-fg:-1,list-bg:-1,gutter:-1,separator:bright-black,scrollbar:bright-black' \
			--color='bg+:-1,fg+:green,hl:green,hl+:green' \
			--color='border:green,label:green,info:bright-black,header:bright-black' \
			--color='prompt:green,pointer:green,marker:green,spinner:green,query:-1,ghost:bright-black' \
			"$@"
}

bt_info_field() {
	bluetoothctl info "$1" | awk -v key="$2" '$1 == key":" {print $2}'
}

wait_for_info_field() {
	local address=$1
	local key=$2
	local expected=$3
	local value

	local i=1
	for ((; i <= TIMEOUT; i++)); do
		value=$(bt_info_field "$address" "$key")
		if [[ $value == "$expected" ]]; then
			return 0
		fi
		sleep 1
	done

	return 1
}

run_bt_commands() {
	local output
	output=$(timeout "$TIMEOUT" bash -lc 'printf "%s\n" "$@" | bluetoothctl' bash "$@" 2>&1)
	local status=$?

	printf "%s\n" "$output" >> "$LOG_FILE"
	return "$status"
}

power_on() {
	local state
	state=$(bluetoothctl show | awk '/PowerState/ {print $2}')

	case $state in
		off)
			bluetoothctl power on > /dev/null
			;;
		off-blocked)
			rfkill unblock bluetooth

			local new_state

			local i=1
			for ((; i <= TIMEOUT; i++)); do
				printf "\rUnblocking Bluetooth... (%d/%d)" $i $TIMEOUT

				new_state=$(bluetoothctl show | awk '/PowerState/ {print $2}')
				if [[ $new_state == on ]]; then
					break
				fi

				sleep 1
			done

			if [[ $new_state != on ]]; then
				notify-send "Bluetooth" "Failed to unblock" -i "package-purge"
				exit 1
			fi
			;;
		*)
			return 0
			;;
	esac

	notify-send "Bluetooth On" -i "network-bluetooth-activated" \
		-h string:x-canonical-private-synchronous:bluetooth
}

get_devices() {
	bluetoothctl -t $TIMEOUT scan on > /dev/null &

	local num

	local i=1
	for ((; i <= TIMEOUT; i++)); do
		printf "\rScanning for devices... (%d/%d)" $i $TIMEOUT
		printf "\nPress [q] to stop\n"

		num=$(bluetoothctl devices | grep -c "^Device")
		printf "\nDevices: %d" "$num"
		printf "\e[3F" # Move cursor 3 lines up

		read -rsn 1 -t 1
		if [[ $REPLY == [Qq] ]]; then
			break
		fi
	done

	printf "\nScanning stopped.\n\n"

	LIST=$(bluetoothctl devices | sed "s/^Device //")
	if [[ -z $LIST ]]; then
		notify-send "Bluetooth" "No devices found" -i "package-broken"
		exit 1
	fi
}

select_device() {
	local header
	printf -v header "%-17s %s" "Address" "Name"

	local options=(
		"--border=sharp"
		"--border-label= Bluetooth Devices "
		"--cycle"
		"--ghost=Search"
		"--gutter= "
		"--header=$header"
		"--height=~100%"
		"--highlight-line"
		"--info=inline-right"
		"--pointer=>"
		"--reverse"
	)

	ADDRESS=$(fzf_ghostty "${options[@]}" <<< "$LIST" | awk '{print $1}')
	if [[ -z $ADDRESS ]]; then
		exit 1
	fi

	local connected
	connected=$(bluetoothctl info "$ADDRESS" | awk '/Connected/ {print $2}')

	if [[ $connected == yes ]]; then
		notify-send "Bluetooth" "Already connected to this device" \
			-i "package-install"
		exit 1
	fi
}

pair_and_connect() {
	local paired
	paired=$(bt_info_field "$ADDRESS" "Paired")

	bluetoothctl scan off > /dev/null
	: > "$LOG_FILE"

	if [[ $paired != yes ]]; then
		printf "Pairing..."

		run_bt_commands \
			"agent on" \
			"default-agent" \
			"pair $ADDRESS" \
			"quit"

		if ! wait_for_info_field "$ADDRESS" "Paired" "yes"; then
			notify-send "Bluetooth" "Failed to pair. See /tmp/yudots-bluetooth.log" \
				-i "package-purge"
			exit 1
		fi
	fi

	run_bt_commands \
		"trust $ADDRESS" \
		"connect $ADDRESS" \
		"quit"

	printf "\nConnecting..."

	local connected
	if ! wait_for_info_field "$ADDRESS" "Connected" "yes"; then
		connected=$(bt_info_field "$ADDRESS" "Connected")
		notify-send "Bluetooth" "Failed to connect. See /tmp/yudots-bluetooth.log" \
			-i "package-purge"
		exit 1
	fi

	notify-send "Bluetooth" "Successfully connected" -i "package-install"
}

main() {
	if [[ $1 == off ]]; then
		bluetoothctl power off
		notify-send 'Bluetooth Off' -i 'network-bluetooth-inactive' \
			-h string:x-canonical-private-synchronous:bluetooth
		return 0
	fi

	printf "\e[?25l" # Make cursor invisible
	power_on
	get_devices

	printf "\e[?25h" # Make cursor visible
	select_device
	pair_and_connect
}

main "$@"
