#!/usr/bin/env bash
#
# Scan, select, pair, and connect to Bluetooth devices
# Passing "off" powers off Bluetooth
#
# Requires bluez-utils (bluetoothctl) and fzf
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    August 19, 2025
# License: MIT

TIMEOUT=10

printf() {
	command printf "$@" >&2
}

fzf_ghostty() {
	env -u FZF_DEFAULT_OPTS -u FZF_DEFAULT_OPTS_FILE \
		fzf \
			--color='fg:-1,bg:-1,list-fg:-1,list-bg:-1,gutter:-1,separator:bright-black,scrollbar:bright-black' \
			--color='bg+:-1,fg+:green,hl:green,hl+:green' \
			--color='border:green,label:green,info:bright-black,header:bright-black' \
			--color='prompt:green,pointer:green,marker:green,spinner:green,query:-1,ghost:bright-black' \
			"$@"
}

power_on() {
	local state
	state=$(bluetoothctl show | awk '/PowerState/ {print $2}')

	case $state in
		off)
			bluetoothctl power on > /dev/null
			;;
		off-blocked)
			rfkill unblock bluetooth

			local new_state

			local i=1
			for ((; i <= TIMEOUT; i++)); do
				printf "\rUnblocking Bluetooth... (%d/%d)" $i $TIMEOUT

				new_state=$(bluetoothctl show | awk '/PowerState/ {print $2}')
				if [[ $new_state == on ]]; then
					break
				fi

				sleep 1
			done

			if [[ $new_state != on ]]; then
				notify-send "Bluetooth" "Failed to unblock" -i "package-purge"
				exit 1
			fi
			;;
		*)
			return 0
			;;
	esac

	notify-send "Bluetooth On" -i "network-bluetooth-activated" \
		-h string:x-canonical-private-synchronous:bluetooth
}

get_devices() {
	bluetoothctl -t $TIMEOUT scan on > /dev/null &

	local num

	local i=1
	for ((; i <= TIMEOUT; i++)); do
		printf "\rScanning for devices... (%d/%d)" $i $TIMEOUT
		printf "\nPress [q] to stop\n"

		num=$(bluetoothctl devices | grep -c "^Device")
		printf "\nDevices: %d" "$num"
		printf "\e[3F" # Move cursor 3 lines up

		read -rsn 1 -t 1
		if [[ $REPLY == [Qq] ]]; then
			break
		fi
	done

	printf "\nScanning stopped.\n\n"

	LIST=$(bluetoothctl devices | sed "s/^Device //")
	if [[ -z $LIST ]]; then
		notify-send "Bluetooth" "No devices found" -i "package-broken"
		exit 1
	fi
}

select_device() {
	local header
	printf -v header "%-17s %s" "Address" "Name"

	local options=(
		"--border=sharp"
		"--border-label= Bluetooth Devices "
		"--cycle"
		"--ghost=Search"
		"--gutter= "
		"--header=$header"
		"--height=~100%"
		"--highlight-line"
		"--info=inline-right"
		"--pointer=>"
		"--reverse"
	)

	ADDRESS=$(fzf_ghostty "${options[@]}" <<< "$LIST" | awk '{print $1}')
	if [[ -z $ADDRESS ]]; then
		exit 1
	fi

	local connected
	connected=$(bluetoothctl info "$ADDRESS" | awk '/Connected/ {print $2}')

	if [[ $connected == yes ]]; then
		notify-send "Bluetooth" "Already connected to this device" \
			-i "package-install"
		exit 1
	fi
}

pair_and_connect() {
	local paired
	paired=$(bluetoothctl info "$ADDRESS" | awk '/Paired/ {print $2}')

	if [[ $paired == no ]]; then
		printf "Pairing..."

		if ! timeout $TIMEOUT bluetoothctl pair "$ADDRESS" > /dev/null; then
			notify-send "Bluetooth" "Failed to pair" -i "package-purge"
			exit 1
		fi
	fi

	printf "\nConnecting..."

	if ! timeout $TIMEOUT bluetoothctl connect "$ADDRESS" > /dev/null; then
		notify-send "Bluetooth" "Failed to connect" -i "package-purge"
		exit 1
	fi

	notify-send "Bluetooth" "Successfully connected" -i "package-install"
}

main() {
	if [[ $1 == off ]]; then
		bluetoothctl power off
		notify-send 'Bluetooth Off' -i 'network-bluetooth-inactive' \
			-h string:x-canonical-private-synchronous:bluetooth
		return 0
	fi

	printf "\e[?25l" # Make cursor invisible
	power_on
	get_devices

	printf "\e[?25h" # Make cursor visible
	select_device
	pair_and_connect
}

main "$@"
