[Appearance]
color_scheme_path=~/.local/share/color-schemes/Matugen.colors
custom_palette=true
icon_theme=breeze
style=Breeze

[Fonts]
fixed="FiraCode Nerd Font Mono,11,-1,5,50,0,0,0,0,0"
general="FiraCode Nerd Font,11,-1,5,50,0,0,0,0,0"